=== Koquda/SEW-24-25/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://www.uniovi.es" elementFormDefault="qualified"
	targetNamespace="http://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="referencias" />
				<xs:element ref="fotos" />
				<xs:element ref="videos" />
				<xs:element ref="coordenadas" />
				<xs:element ref="tramos" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="fecha" type="xs:date" use="required" />
			<xs:attribute name="hora" type="xs:time" use="required" />
			<xs:attribute name="vueltas" type="xs:integer" use="required" />
			<xs:attribute name="localidad" type="xs:string" use="required" />
			<xs:attribute name="pais" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="decimalPositivo">
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:minInclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="medida" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="decimalPositivo">
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:minInclusive value="0"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="medida" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence minOccurs="3" maxOccurs="unbounded">
				<xs:element ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotos">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="5">
				<xs:element ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="foto" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="3">
				<xs:element ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="longitud" type="xs:decimal" use="required" />
					<xs:attribute name="latitud" type="xs:decimal" use="required" />
					<xs:attribute name="altitud" type="xs:decimal" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="coordenadas" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:integer" />
</xs:schema>

=== Koquda/SEW-24-25/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<circuito 
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://www.uniovi.es"
    nombre="Red Bull Ring"
    fecha="2024-06-30"
    hora="15:00:00"
    vueltas="71"
    localidad="Knittelfeld"
    pais="Austria"
>
    <longitud medida="m">
        <decimalPositivo>4318</decimalPositivo>
    </longitud>
    <anchuraMedia medida="m">
        <decimalPositivo>12.5</decimalPositivo>
    </anchuraMedia>
    <referencias>
        <referencia>https://www.formula1.com/en/information/austria-red-bull-ring-spielberg.1s7EC2bGta7o1thZkVPbbq</referencia>
        <referencia>https://www.boxrepsol.com/es/motogp/10-cosas-red-bull-ring/#:~:text=Concretamente%2C%20est%C3%A1%20677%20metros%20por,circuito%20es%20de%2065%20metros.</referencia>
        <referencia>https://github.com/bacinger/f1-circuits/blob/master/circuits/at-1969.geojson?short_path=7f9a04b</referencia>
    </referencias>
    <fotos>
        <foto>circuito1.jpg</foto>
        <foto>circuito2.jpg</foto>
        <foto>circuito3.jpg</foto>
    </fotos>
    <videos>
        <video>circuitoVideo.mp4</video>
    </videos>
    <coordenadas
        latitud="14.764861"
        longitud="47.219963"
        altitud="677"
    ></coordenadas>
    <tramos>

        <punto>
            <longitud medida='m'>
                <decimalPositivo>73.76</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76487472745423"
                latitud="47.21994278464728"
                altitud="678.6633948688855"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>53.59</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76393065640733"
                latitud="47.21977270075171"
                altitud="678.5582411576454"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>46.56</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76323401998832"
                latitud="47.21968100602513"
                altitud="680.0705773160921"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>54.34</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76264662210966"
                latitud="47.21955378435345"
                altitud="682.2177632204254"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>35.77</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76194898792896"
                latitud="47.21943407779996"
                altitud="685.9427170042603"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>29.14</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76149075422736"
                latitud="47.21935262205427"
                altitud="688.6411283371654"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>15.74</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76112103748106"
                latitud="47.21927764720042"
                altitud="691.9768035417418"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>22.97</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76091390220761"
                latitud="47.21929301358031"
                altitud="693.0656814487281"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>32.36</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76074969420293"
                latitud="47.21946689676203"
                altitud="694.6531603278697"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>34.09</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76054403694253"
                latitud="47.21972220995164"
                altitud="695.7595604136785"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>50.79</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.76027119086558"
                latitud="47.21996646075331"
                altitud="696.3768786384046"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>48.85</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75987917318552"
                latitud="47.2203375522831"
                altitud="697.6585611796343"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>55.04</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.7594959620722"
                latitud="47.22069147315351"
                altitud="696.2312646107606"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>50.10</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75907041682662"
                latitud="47.2210933565151"
                altitud="697.5500052602157"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>59.55</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75870760697256"
                latitud="47.22147060574129"
                altitud="697.7148965841692"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>56.27</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75831962449059"
                latitud="47.22193680722316"
                altitud="699.3966313386615"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>90.03</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75795806947927"
                latitud="47.22237930068696"
                altitud="699.4728532634972"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>78.67</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75746188871869"
                latitud="47.22311550596871"
                altitud="699.531294585785"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>77.25</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.7570252082737"
                latitud="47.22375787155819"
                altitud="702.9891295374679"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>45.45</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75650821234877"
                latitud="47.22435731212169"
                altitud="708.2363432792893"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>53.96</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75614894328383"
                latitud="47.22468522216391"
                altitud="711.7770870629811"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>62.27</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75563384363756"
                latitud="47.22502160828961"
                altitud="717.4567489233203"
            ></coordenadas>
            <sector>1</sector>
        </punto>
        <punto>
            <longitud medida='m'>
                <decimalPositivo>0</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75504790055818"
                latitud="47.22541565798387"
                altitud="725.3589382177149"
            ></coordenadas>
            <sector>1</sector>
        </punto>

        <punto>
            <longitud medida='m'>
                <decimalPositivo>31.59</decimalPositivo>
            </longitud>
            <coordenadas
                longitud="14.75456565324578"
                latitud="47.22574906392531"
