=== Koquda/SEW-24-25/xml/circuito.dtd
<!ELEMENT circuito 
    (
        longitud, 
        anchuraMedia,
        referencias,
        fotos,
        videos,
        coordenadas,
        tramos
    )
>
<!ATTLIST circuito 
    nombre CDATA #REQUIRED
    fecha CDATA #REQUIRED
    hora NMTOKEN #REQUIRED
    vueltas NMTOKEN #REQUIRED
    localidad CDATA #REQUIRED
    pais CDATA #REQUIRED
>

<!-- Elementos de medida -->
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud medida CDATA #REQUIRED>
<!ELEMENT anchuraMedia (#PCDATA)>
<!ATTLIST anchuraMedia medida CDATA #REQUIRED>

<!-- Referencias TODO: revisar elemento referencia -->
<!ELEMENT referencias (referencia)+>
<!ELEMENT referencia (#PCDATA)>

<!-- Lista de fotos de 1 a 5 TODO: revisar elemento foto-->
<!ELEMENT fotos (foto)+>
<!ELEMENT foto (#PCDATA)>
<!-- Lista de videos de 0 a 3 TODO: revisar elemento video-->
<!ELEMENT videos (video)*>
<!ELEMENT video (#PCDATA)>

<!-- Coordenadas -->
<!ELEMENT coordenadas (#PCDATA)>
<!ATTLIST coordenadas
    longitud NMTOKEN #REQUIRED
    latitud NMTOKEN #REQUIRED
    altitud NMTOKEN #REQUIRED
>

<!-- Tramos -->
<!ELEMENT tramos (punto+)>
<!ELEMENT punto (longitud, coordenadas, sector)>
<!ELEMENT sector (#PCDATA)>

=== Koquda/SEW-24-25/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito
    nombre="Red Bull Ring"
    fecha="30-06-2024"
    hora="15:00"
    vueltas="71"
    localidad="Knittelfeld"
    pais="Austria"
>
    <longitud medida="m">4318</longitud>
    <anchuraMedia medida="m">12.5</anchuraMedia>
    <referencias>
        <referencia></referencia>
        <referencia></referencia>
        <referencia></referencia>
    </referencias>
    <fotos>
        <foto>circuito1.jpg</foto>
        <foto>circuito2.jpg</foto>
        <foto>circuito3.jpg</foto>
    </fotos>
    <videos>
        <video></video>
    </videos>
    <coordenadas
        latitud="todo"
        longitud="todo"
        altitud="todo"
    ></coordenadas>
    <tramos>
        <tramo sector="1">
            <longitud medida="km">todo</longitud>
            <coordenadas
                latitud="todo"
                longitud="todo"
                altitud="todo"
            ></coordenadas>
        </tramo>
    </tramos>
</circuito>
